Blockly.Msg.HUSKYLENS_IS_READY_MESSAGE = "HUSKYLENS is ready ?";
Blockly.Msg.HUSKYLENS_IS_READY_TOOLTIP = "get status of HUSKYLENS";

Blockly.Msg.HUSKYLENS_MODE_MESSAGE = "HUSKYLENS set mode %1";
Blockly.Msg.HUSKYLENS_MODE_TOOLTIP = "";

Blockly.Msg.HUSKYLENS_BLOCK_IS_READY_MESSAGE = "HUSKYLENS block %1 is ready ?";
Blockly.Msg.HUSKYLENS_BLOCK_IS_READY_TOOLTIP = "";

Blockly.Msg.HUSKYLENS_BLOCK_GET_POS_MESSAGE = "HUSKYLENS block %1 get position %2";
Blockly.Msg.HUSKYLENS_BLOCK_GET_POS_TOOLTIP = "";

Blockly.Msg.HUSKYLENS_BLOCK_GET_SIZE_MESSAGE = "HUSKYLENS block %1 get size %2";
Blockly.Msg.HUSKYLENS_BLOCK_GET_SIZE_TOOLTIP = "";

Blockly.Msg.HUSKYLENS_ARROW_IS_READY_MESSAGE = "HUSKYLENS arrow is ready ?";
Blockly.Msg.HUSKYLENS_ARROW_IS_READY_TOOLTIP = "";

Blockly.Msg.HUSKYLENS_ARROW_GET_POS_MESSAGE = "HUSKYLENS arrow get position %1";
Blockly.Msg.HUSKYLENS_ARROW_GET_POS_TOOLTIP = "";
